### ISSUE TITLE
レシピを「食べたい」に設定しようとするとエラーになる

### ISSUE THREAD

**Issue by ryota0222** [reciperu/reciperu-app#40]
サーバー側のログは以下の通り

> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Query: SELECT "public"."users"."user_id", "public"."users"."name", "public"."users"."image_url", "public"."users"."active_status", "public"."users"."uid", "public"."users"."space_role", "public"."users"."space_id" FROM "public"."users" WHERE ("public"."users"."uid" = $1 AND 1=1) LIMIT $2 OFFSET $3
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Params: \["k09xWjzN9qYOjj9uCtNhIRElYKL2",1,0\]
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Duration: 2 ms
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Query: INSERT INTO "public"."requested_recipes" ("user_id","recipe_id","created_at") VALUES ($1,$2,$3) RETURNING "public"."requested_recipes"."user_id", "public"."requested_recipes"."recipe_id", "public"."requested_recipes"."created_at"
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Params: \["clt062wiw0005j5qxsgc2luft","cltitmsrz0001j50dzx8nd5q9","2024-04-08 07:32:20.183 UTC"\]
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] Duration: 1 ms
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM     LOG \[PrismaService\] error:
>
> Invalid `this.prismaService.requestedRecipe.create()` invocation in
>
> /Users/matsumotoryouta/work/projects/reciperu/reciperu-api-app/src/infrastructure/database/prisma/repositories/prisma.requested-recipe.repository.ts:13:46
>
> 10   this.prismaService = prismaService;
>
> 11 }
>
> 12 async create(userId: string, recipeId: string): Promise<void> {
>
> → 13   await this.prismaService.requestedRecipe.create(
>
> Unique constraint failed on the fields: (`user_id`,`recipe_id`)
>
> \[Nest\] 98615  - 04/08/2024, 4:32:20 PM   ERROR \[ExceptionsHandler\]
>
> Invalid `this.prismaService.requestedRecipe.create()` invocation in
>
> /Users/matsumotoryouta/work/projects/reciperu/reciperu-api-app/src/infrastructure/database/prisma/repositories/prisma.requested-recipe.repository.ts:13:46
>
> 10   this.prismaService = prismaService;
>
> 11 }
>
> 12 async create(userId: string, recipeId: string): Promise<void> {
>
> → 13   await this.prismaService.requestedRecipe.create(
>
> Unique constraint failed on the fields: (`user_id`,`recipe_id`)
>
> PrismaClientKnownRequestError:
>
> Invalid `this.prismaService.requestedRecipe.create()` invocation in
>
> /Users/matsumotoryouta/work/projects/reciperu/reciperu-api-app/src/infrastructure/database/prisma/repositories/prisma.requested-recipe.repository.ts:13:46

**Comment by masatotezuka** [comment]
@ryotanny 

食べたいレシピのフラグを外す時に、`DELETE `recipes/:id/requests のAPI呼んでいる？<br>API側ではなくアプリ側の問題だと思うんだけど、、<br>単に作成したレコードを削除していないから、レシピ一覧から食べたい料理に登録してもすでに食べたい料理に登録されていますよって怒られているだけだと思う！

**Comment by masatotezuka** [comment]
@ryotanny 

これ解決したよね？
